apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: demo-cluster
  name: demo-cluster
---
apiVersion: devops.k8s.io/v1
kind: Cluster
metadata:
  name: demo-cluster
  namespace: demo-cluster
  annotations:
    "k8s.io/action": EnsureDeployCni
    "k8s.io/apiSvcVip": 172.16.18.6
spec:
  pause: false
  tenantID: k8s
  displayName: demo
  type: baremetal
  operatingSystem: ubuntu
  version: v1.18.12
  networkType: ens34
  clusterCIDR: 172.16.99.0/24
  serviceCIDR: 172.16.100.0/24
  dnsDomain: cluster.local
  publicAlternativeNames:
    - vip.demo.k8s.io
  features:
    ipvs: true
    internalLB: true
    enableMasterSchedule: true
    ha:
      thirdParty:
        vip: "172.16.18.240"
        vport: 6443
    hooks:
      cniInstall: flannel
  properties:
    maxNodePodNum: 64
  machines:
    - ip: 172.16.18.6
      port: 22
      username: root
      password: "123456"
  apiServerExtraArgs:
    audit-log-maxage: "30"
    audit-log-maxbackup: "3"
    audit-log-maxsize: "100"
    audit-log-truncate-enabled: "true"
    audit-log-path: "/var/log/kubernetes/k8s-audit.log"
  controllerManagerExtraArgs:
    "bind-address": "0.0.0.0"
  schedulerExtraArgs:
    "bind-address": "0.0.0.0"
  dockerExtraArgs:
    registry-mirrors: https://4xr1qpsp.mirror.aliyuncs.com
    version: 19.03.13
