apiVersion: devops.k8s.io/v1
kind: Machine
metadata:
  labels:
    name: 10.248.224.210
    clusterName: example-cluster
  name: 10.248.224.210
  namespace: example-cluster
spec:
  clusterName: example-cluster
  type: baremetal
  machine:
    ip: 10.248.224.210
    port: 22
    username: root
    password: "UVK4AfcSuEQTK-LH-Lk1Fy"
  feature:
    hooks:
      installType: kubeadm
