
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - devops.k8s.io
  resources:
  - virtulclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.k8s.io
  resources:
  - virtulclusters/status
  verbs:
  - get
  - patch
  - update
