{{- if and .Values.rbac.create .Values.contour.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "contour.fullname" .}}:contour
  labels: {{- include "contour.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - nodes
  - pods
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "networking.k8s.io"
  resources:
  - "ingresses/status"
  verbs:
  - get
  - list
  - watch
  - patch
  - post
  - update
- apiGroups:
  - projectcontour.io
  resources:
  - extensionservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - projectcontour.io
  resources:
  - extensionservices/status
  verbs:
  - create
  - get
  - update
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies
  - tlscertificatedelegations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies/status
  verbs:
  - create
  - get
  - update
- apiGroups: ["networking.x.k8s.io"]
  resources: ["gatewayclasses", "gateways", "httproutes", "tcproutes"]
  verbs:
  - get
  - list
  - watch
  - put
  - post
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "contour.fullname" .}}:contour-leaderelection
  labels: {{- include "contour.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "contour.fullname" .}}:contour-certgen
  labels: {{- include "contour.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "contour.fullname" .}}:contour
  labels: {{- include "contour.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "contour.fullname" .}}:contour
subjects:
  - kind: ServiceAccount
    name: {{ include "contour.contourServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "contour.fullname" .}}:contour-leaderelection
  labels: {{- include "contour.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "contour.fullname" . }}:contour-leaderelection
subjects:
  - kind: ServiceAccount
    name: {{ include "contour.contourServiceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "contour.fullname" .}}:contour-certgen
  labels: {{- include "contour.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "contour.fullname" .}}:contour-certgen
subjects:
  - kind: ServiceAccount
    name: {{ include "contour.contourCertGenServiceAccountName" . }}
{{- end }}

{{- if and .Values.contour.serviceAccount.create .Values.contour.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "contour.contourServiceAccountName" . }}
  labels: {{- include "contour.labels" . | nindent 4 }}
    app.kubernetes.io/component: contour
  {{- end }}
  {{- if .Values.contour.certgen.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "contour.contourCertGenServiceAccountName" . }}
  labels: {{- include "contour.labels" . | nindent 4 }}
    app.kubernetes.io/component: contour
  {{- end }}
  {{- if and .Values.envoy.serviceAccount.create .Values.envoy.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "envoy.envoyServiceAccountName" . }}
  labels: {{- include "contour.labels" . | nindent 4 }}
    app.kubernetes.io/component: envoy
{{- end }}
