---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
  - description: dke kubeadm bootstrap token
    token: huzozk.8c1f3ev88ugqzmbp
    ttl: 0s
certificateKey: db4f1fdbf6c1b7d148612cb3aadc55d765c534f56140855cf56a5dbece2b0111
localAPIEndpoint:
  advertiseAddress: 172.16.18.6
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  certSANs:
    - 127.0.0.1
    - 172.16.18.240
    - 172.16.18.6
    - localhost
    - vip.demo.k8s.io
  extraArgs:
    audit-log-maxage: "30"
    audit-log-maxbackup: "3"
    audit-log-maxsize: "100"
    audit-log-path: /var/log/kubernetes/k8s-audit.log
    audit-log-truncate-enabled: "true"
    token-auth-file: /etc/kubernetes/known_tokens.csv
  extraVolumes:
    - hostPath: /etc/kubernetes
      mountPath: /etc/kubernetes
      name: vol-dir-0
    - hostPath: /var/log/kubernetes
      mountPath: /var/log/kubernetes
      name: audit-dir-0
      pathType: DirectoryOrCreate
certificatesDir: /etc/kubernetes/pki/
clusterName: demo-cluster
controlPlaneEndpoint: vip.demo.k8s.io:6443
controllerManager:
  extraArgs:
    allocate-node-cidrs: "true"
    bind-address: 0.0.0.0
    cluster-cidr: 172.16.99.0/24
    node-cidr-mask-size: "26"
  extraVolumes:
    - hostPath: /etc/kubernetes
      mountPath: /etc/kubernetes
      name: vol-dir-0
dns:
  type: CoreDNS
etcd: {}
imageRepository: docker.io/wtxue
kubernetesVersion: v1.18.12
networking:
  dnsDomain: cluster.local
  serviceSubnet: 172.16.100.0/24
scheduler:
  extraArgs:
    bind-address: 0.0.0.0
  extraVolumes:
    - hostPath: /etc/kubernetes
      mountPath: /etc/kubernetes
      name: vol-dir-0
---
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous: {}
  webhook:
    cacheTTL: 0s
  x509: {}
authorization:
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s
cpuManagerReconcilePeriod: 0s
evictionPressureTransitionPeriod: 0s
fileCheckFrequency: 0s
httpCheckFrequency: 0s
imageMinimumGCAge: 0s
kind: KubeletConfiguration
kubeReserved:
  cpu: 100m
  memory: 500Mi
maxPods: 64
nodeStatusReportFrequency: 0s
nodeStatusUpdateFrequency: 0s
runtimeRequestTimeout: 0s
streamingConnectionIdleTimeout: 0s
syncFrequency: 0s
systemReserved:
  cpu: 100m
  memory: 500Mi
volumeStatsAggPeriod: 0s
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: ""
clientConnection:
  acceptContentTypes: ""
  burst: 0
  contentType: ""
  kubeconfig: ""
  qps: 0
clusterCIDR: ""
configSyncPeriod: 0s
conntrack:
  maxPerCore: null
  min: null
  tcpCloseWaitTimeout: null
  tcpEstablishedTimeout: null
detectLocalMode: ""
enableProfiling: false
healthzBindAddress: ""
hostnameOverride: ""
iptables:
  masqueradeAll: false
  masqueradeBit: null
  minSyncPeriod: 0s
  syncPeriod: 0s
ipvs:
  excludeCIDRs: null
  minSyncPeriod: 0s
  scheduler: ""
  strictARP: false
  syncPeriod: 0s
  tcpFinTimeout: 0s
  tcpTimeout: 0s
  udpTimeout: 0s
kind: KubeProxyConfiguration
metricsBindAddress: ""
mode: ipvs
nodePortAddresses: null
oomScoreAdj: null
portRange: ""
showHiddenMetricsForVersion: ""
udpIdleTimeout: 0s
winkernel:
  enableDSR: false
  networkName: ""
  sourceVip: ""
---


kubeadm init phase kubelet-start --node-name=172.16.18.6 --config=/etc/kubernetes/kubeadm-config.yaml -v 9

kubeadm init phase control-plane all --config=/etc/kubernetes/kubeadm-config.yaml -v 9


kubeadm init phase etcd local --config=/etc/kubernetes/kubeadm-config.yaml -v 9
